[package]
name = "cargo-bin"
version = "0.1.0"
authors = ["gensmusic <gensmusic@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml_edit = "0.2.0"
anyhow = "1.0.32"