[package]
name = "cargo-bin"
version = "0.1.0"
authors = ["Xuefei Ren <renxf@ifeng.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
